#!/bin/bash
BITRATE=64
OUTDIR="."
if [ "$1" != "" ]; then
    BITRATE=$1
fi
if [ "$2" != "" ]; then
    OUTDIR=$2
fi

echo "Encoding with bitrate ${BITRATE} in ${OUTDIR}"

for file in "*.mp3" ; do
	FILE=`basename "${file}" .mp3`
	OUTFILE="$OUTDIR/$FILE.ogg"
		
	avconv -i "$file" -f flac - | opusenc --discard-pictures --bitrate $BITRATE - "$OUTFILE"
done;
